kind: Service    
apiVersion: v1     
metadata:
  name: myapp 
spec:
  selector:
    app: myapp   
  ports:        
  - name: http-web    
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: strand-configmap
data:
  gitrepo: https://github.com/sstrand72/k8s-devops-new.git
  image: SwissAlps.jpg
  
---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
spec:
  containers: 
  - name: cdn
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: cdn
      initContainers:
      - name: git
        image: alpine/git:latest
        command: ["git"]
        args: ["clone", "$(GITREPO)", "/cdn"]
        env:
        - name: GITREPO
          valueFrom:
            configMapKeyRef:
              name: strand-configmap
              key: GITREPO
        volumeMounts:
        - mountPath: /cdn
          name: cdn
      volumes:
      - name: cdn
        emptyDir: {}
       
---



