apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
spec:
  containers: 
  - name: 
    image: nginx:latest
    command: 
  initContainers:
  - name: init-step1 # INIT 1 
    image: alpine:/git:latest
    command: 
  - name: init-step2
    image: 
    command: 
    
---

