kind: Service    
apiVersion: v1     
metadata:
  name: myapp 
spec:
  selector:
    app: myapp   
  ports:        
  - name: http-web    
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: strand-configmap
data:
  gitrepo: https://github.com/sstrand72/k8s-devops-new.git
  image: SwissAlps.jpg
  
---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
spec:
  containers: 
  - name: 
    image: nginx:latest
    command: 
  initContainers:
  - name: init-step1 # INIT 1 
    image: alpine:/git:latest
    command: 
  - name: init-step2
    image: 
    command: 
       
---



