kind: Service    
apiVersion: v1     
metadata:
  name: strand-app 
spec:
  selector:
    app: frontend   
  ports:        
  - name: http-web    
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
