apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
  selector:
    app: guestbook-ui
  type: LoadBalancer
